[workspace]

members = [
    "topper-core",
    "topper-bt",
    "topper-derive",
    "topper-aetolia",
    "topper-aetolia-mudlet",
    "topper-aetolia-editor",
    "topper-core-mudlet",
    "topper-sect-parser",
]
