pub mod agent;
pub mod branching;
pub mod general;
pub mod limbs;
pub mod sentinel;
pub mod shapeshifter;
pub mod syssin;
pub mod zealot;
pub use crate::timeline::CType;
pub use agent::*;
pub use branching::*;
pub use general::*;
pub use limbs::*;
pub use sentinel::*;
pub use shapeshifter::*;
pub use syssin::*;
pub use zealot::*;
pub const BALANCE_SCALE: f32 = 100.0;
